### ISSUE TITLE
proposal: to integrate with Gutenberg

### ISSUE THREAD

**Issue by ptcmyanmar** [drov0/steempress#11]
I posted about this in utopian-io.

Here is the link:

https://steemit.com/utopian-io/@ptcmyanmar/utopian-io-suggestion-to-steempress-to-integrate-with-gutenberg

**Comment by drov0** [comment]
Gutenberg compatibility will be added soon

**Comment by ptcmyanmar** [comment]
thanks.

**Comment by drov0** [comment]
"soon" haha. Anyways, it's done although a few bugs still remain.
