### ISSUE TITLE
Steempress Signature Is Not Rendered Correctly in Steemit / Steempeak

### ISSUE THREAD

**Issue by propertunist** [drov0/steempress#13]
### Expected behavior

Posts made via Steempress should have a correctly formatted string of HTML text at their footer highlighting that Steempress was used.

### Actual Behavior

The signature inserted by Steempress at the end of the posts is not being rendered correctly.

This [post](https://blog.steemocean.com/top-voters/top-20-voters-20-october-2018/) in my wordpress site was submitted to Steem [here](https://steemit.com/steemocean/@steem-ocean/thetop20biggestvotersonthesteemblockchain20-25october2018-c5epaxrhso) and as you can see, the end of the post is presented as html instead of pure text.

![Selection_139.png](https://files.steempeak.com/file/steempeak/ura-soul/swQvCYPb-Selection_139.png)

### Technical Analysis

I suspect this may be because the text is not being converted to the correct character encoding prior to being submitted to the blockchain. E.g. The text appears in steem editors as:

![Selection_140.png](https://files.steempeak.com/file/steempeak/steem-ocean/LO6n3apv-Selection_140.png)

Instead of as correctly rendered (normal) HTML.

**Comment by drov0** [comment]
Thanks, looks like an issue with sanitation, I'll look at it.

**Comment by propertunist** [comment]
@drov0 You are welcome! I have a couple more bugs to log here, I'll do that asap. 
Also, I recall that you were using your delegation to upvote posts that are created via the plugin. I just started using steempress on my new site for steemocean.com and just want to check if there's anything in particular I need to do to get those votes.. Is there a set of guidelines somewhere? Thanks

**Comment by drov0** [comment]
>  I have a couple more bugs to log here, I'll do that asap. 

Awesome ! 

>  I just started using steempress on my new site for steemocean.com and just want to check if there's anything in particular I need to do to get those votes.. Is there a set of guidelines somewhere? Thanks

Not really, it's more of a "write good content and get noticed". I have added you to the whitelist so you are now eligible to votes :)

**Comment by propertunist** [comment]
Oh excellent, thankyou! I have a lot going on here and now a bit ill (before my trip to steemfest..), but i'll try to get these issues logged soon.

**Comment by propertunist** [comment]
@drov0 -  I have updated the steempress plugin to version 2.0.2, but my new post still has a similar problem: 
https://steemit.com/steemocean/@steem-ocean/top50steemiansinthesteemoceanvoterrankingindexforbenevolence-hvu3qi4cp5

In case the new release was intended to include your fix.

**Comment by drov0** [comment]
Hello, 
you need to re-save your settings after the update otherwise it's still the old footer with issues that's being sent. Please tell me if that fixed the issue for you.

**Comment by propertunist** [comment]
@drov0 aha ok, thanks. yes that has fixed it, thanks.

**Comment by drov0** [comment]
Awesome.
